[package]
name = "botzilla"
version = "0.1.0"
authors = ["Benjamin Bouvier <public@benj.me>"]
edition = "2018"

[dependencies]
ruma-client = "0.2.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
url = "1.7.2"
tokio = "0.1.18"
futures = "0.1.26"
